---
- hosts: appservers
  vars:
   username: nitish

  tasks:
   - name: Install apache2 server
     apt: 
       name: apache2 
       state: present

   - name: Start apache2 service
     service:
       name: apache2
       state: started
   
   - name: copy website content using jinja2
     template:
       src: templates/index.j2
       dest: /var/www/html/index.html
     notify:
       - Restart apache

   - name: copy file 
     copy:
       src: files/test.txt
       dest: /text.txt
     notify:
      - Restart apache     

  handlers:
   - name: Restart apache
     service:
       name: apache2
       state: restarted

- hosts: dbservers
  
  tasks:
   #- name: Install mysql server
   - apt:
       name: mysql-server
       state: present
   - name: Start mysql server
     service: 
       name: mysql
       state: started
  
